env:
  browser: false
  es2021: true
extends: eslint:recommended
globals:
  URL: readonly
  console: readonly
  process: readonly
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
